plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'net.neoforged.gradle.userdev' version '7.0.+'
}

version = '1.31'
group = 'bl4ckscor3.mod.ceilingtorch'

base {
	archivesName = 'ceilingtorch-1.21.4'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

runs {
	configureEach {
		systemProperty 'forge.logging.console.level', 'debug'
		modSource project.sourceSets.main
	}

	client {
		workingDirectory project.file('run/client')
	}

	server {
		workingDirectory project.file('run/server')
		argument '-nogui'
	}
}

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
	implementation 'net.neoforged:neoforge:21.4.124'
//	implementation 'curse.maven:jei-238222:5846880'

	implementation "curse.maven:additional-lights-384991:5998264"
	implementation "curse.maven:bagus-lib-866533:6338404" //tofucraftreload dependency
	implementation "curse.maven:common-capabilities-247007:6279937" //integrated dynamics dependency
	implementation "curse.maven:cyclops-core-232758:6279942" //integrated dynamics dependency
    implementation "curse.maven:gaia-dimension-302529:6097705"
	implementation "curse.maven:integrated-dynamics-236307:6331569"
	implementation "curse.maven:sbm-bone-torch-238695:5978261"
	implementation "curse.maven:tofucraftreload-317469:6327857"
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title": "Ceiling Torch",
                    "Specification-Vendor": "bl4ckscor3",
                    "Specification-Version": "${version}",
                    "Implementation-Title": "Ceiling Torch",
                    "Implementation-Version": "${version}",
                    "Implementation-Vendor": "bl4ckscor3"])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
	options.release = 21
}