plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'net.neoforged.moddev' version '2.0.105'
}

version = '1.33'
group = 'bl4ckscor3.mod.ceilingtorch'

base {
	archivesName = 'ceilingtorch-1.21.8'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

neoForge {
	version = "21.8.54"

	runs {
		configureEach {
			logLevel = org.slf4j.event.Level.DEBUG
			gameDirectory = project.file("run/" + name)
			ideName = "CeilingTorch " + ideName.get()
		}

		client {
			client()
		}

		server {
			server()
			programArgument('-nogui')
		}
	}

	mods {
		ceilingtorch {
			sourceSet(sourceSets.main)
		}
	}
}

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
	implementation 'curse.maven:jei-238222:7025033'

	implementation "curse.maven:additional-lights-384991:6743127"
	implementation "curse.maven:adorn-for-forge-438784:7066177"
	implementation "curse.maven:bagus-lib-866533:6938856" //tofucraftreload dependency
	implementation "curse.maven:colored-torches-1161227:6894097"
	implementation "curse.maven:common-capabilities-247007:7248760" //integrated dynamics dependency
	implementation "curse.maven:cyclops-core-232758:7248797" //integrated dynamics dependency
	implementation "curse.maven:gaia-dimension-302529:7021519"
	implementation "curse.maven:integrated-dynamics-236307:7271142"
	implementation "curse.maven:reliquary-reincarnations-241319:8398744"
	implementation "curse.maven:sbm-bone-torch-238695:6675364"
	implementation "curse.maven:tofucraftreload-317469:7005134"
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title": "Ceiling Torch",
                    "Specification-Vendor": "bl4ckscor3",
                    "Specification-Version": "${version}",
                    "Implementation-Title": "Ceiling Torch",
                    "Implementation-Version": "${version}",
                    "Implementation-Vendor": "bl4ckscor3"])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
	options.release = 21
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}