plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'net.neoforged.gradle.userdev' version '7.0.+'
}

version = '1.30'
group = 'bl4ckscor3.mod.ceilingtorch'

base {
	archivesName = 'ceilingtorch-1.21'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')

runs {
	configureEach {
		systemProperty 'forge.logging.console.level', 'debug'
		modSource project.sourceSets.main
	}

	client {
		workingDirectory project.file('run/client')
	}

	server {
		workingDirectory project.file('run/server')
		argument '-nogui'
	}
}

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
	implementation 'net.neoforged:neoforge:21.1.73'
	implementation 'curse.maven:jei-238222:5525108'

	implementation "curse.maven:additional-lights-384991:5504182"
	implementation "curse.maven:adorn-for-forge-438784:5773274"
	implementation "curse.maven:architectury-api-419699:5521987" //bamboo everything dependency
	implementation "curse.maven:athena-841890:5431579" //bamboo everything dependency
	implementation "curse.maven:bagus-lib-866533:5511022" //tofucraftreload dependency
	implementation "curse.maven:bamboo-everything-331723:5438627"
	implementation "curse.maven:chipped-456956:5506938"
	implementation "curse.maven:gaia-dimension-302529:5773438"
	implementation "curse.maven:geckolib-388172:5460144" //occultism dependency
	implementation "curse.maven:modonomicon-538392:5519525" //occultism dependency
	implementation "curse.maven:occultism-361026:5525534"
	implementation "curse.maven:resourceful-lib-570073:5483169" //bamboo everything dependency
	implementation "curse.maven:sbm-bone-torch-238695:5513932"
	implementation "curse.maven:silent-gear-297039:5846318"
	implementation "curse.maven:silent-lib-242998:5730272" //silent gear and torch bandolier dependency
	implementation "curse.maven:smartbrainlib-661293:5513418" //occultism dependency
	implementation "curse.maven:tofucraftreload-317469:5526459"
	implementation "curse.maven:torch-bandolier-299337:5641604"
	implementation "curse.maven:xycraft-653786:5526989" // xycraft world dependency
	implementation "curse.maven:xycraft-world-653789:5526991"
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title": "Ceiling Torch",
                    "Specification-Vendor": "bl4ckscor3",
                    "Specification-Version": "${version}",
                    "Implementation-Title": "Ceiling Torch",
                    "Implementation-Version": "${version}",
                    "Implementation-Vendor": "bl4ckscor3"])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
	options.release = 21
}