modLoader="javafml"
loaderVersion="[38,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/CeilingTorch/blob/1.18/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/CeilingTorch/issues"
authors="bl4ckscor3"

[[mods]]
	modId="ceilingtorch"
	version="${file.jarVersion}"
	displayName="Ceiling Torch"
	description='''Makes torches placeable on the ceiling.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/ceiling-torch"

[[dependencies.ceilingtorch]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ceilingtorch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"