modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/CeilingTorch/blob/1.18/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/CeilingTorch/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ceiling-torch"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="ceilingtorch" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ceiling Torch" #mandatory
description='''Makes torches placeable on the ceiling.''' #mandatory

[[dependencies.ceilingtorch]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ceilingtorch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"