modLoader="javafml"
loaderVersion="[46,)"
license="MIT https://github.com/bl4ckscor3/CeilingTorch/blob/1.19/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/CeilingTorch/issues"
authors="bl4ckscor3"

[[mods]]
	modId="ceilingtorch"
	version="${file.jarVersion}"
	displayName="Ceiling Torch"
	description='''Makes torches placeable on the ceiling.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/ceiling-torch"

[[dependencies.ceilingtorch]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ceilingtorch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
