modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory
issueTrackerURL="https://github.com/bl4ckscor3/CeilingTorch/issues"
displayURL="http://minecraft.curseforge.com/projects/ceiling-torch"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="ceilingtorch" #mandatory
version="v1.0" #mandatory
displayName="Ceiling Torch" #mandatory
description='''Makes vanilla torches placeable on the ceiling.''' #mandatory

[[dependencies.ceilingtorch]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ceilingtorch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"