modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/bl4ckscor3/CeilingTorch/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ceiling-torch"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="ceilingtorch" #mandatory
version="v1.6" #mandatory
displayName="Ceiling Torch" #mandatory
description='''Makes torches placeable on the ceiling.''' #mandatory

[[dependencies.ceilingtorch]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ceilingtorch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"