modLoader="javafml"
loaderVersion="[33,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/CeilingTorch/blob/1.16/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/CeilingTorch/issues"
authors="bl4ckscor3"

[[mods]]
	modId="ceilingtorch"
	version="${version}"
	displayName="Ceiling Torch"
	description='''Makes torches placeable on the ceiling.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/ceiling-torch"

[[dependencies.ceilingtorch]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ceilingtorch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"