package bl4ckscor3.mod.ceilingtorch;

import java.util.Arrays;

import net.minecraft.block.Block;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;

@Mod(modid=CeilingTorch.MODID, name=CeilingTorch.NAME, version=CeilingTorch.VERSION, acceptedMinecraftVersions="[" + CeilingTorch.MC_VERSION + "]")
@EventBusSubscriber
public class CeilingTorch
{
	public static final String MODID = "ceilingtorch";
	public static final String NAME = "Ceiling Torch";
	public static final String VERSION = "v1.0.1";
	public static final String MC_VERSION = "1.12.2";
	@ObjectHolder(MODID + ":torch")
	public static final Block TORCH = null;
	@ObjectHolder(MODID + ":unlit_redstone_torch")
	public static final Block UNLIT_REDSTONE_TORCH = null;
	@ObjectHolder(MODID + ":redstone_torch")
	public static final Block REDSTONE_TORCH = null;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		ModMetadata meta = event.getModMetadata();

		meta.authorList = Arrays.asList(new String[]{"bl4ckscor3"});
		meta.autogenerated = false;
		meta.description = "Makes vanilla torches placeable on the ceiling.";
		meta.modId = MODID;
		meta.name = NAME;
		meta.version = VERSION;
		meta.url = "https://minecraft.curseforge.com/projects/ceiling-torch";
	}

	@SubscribeEvent
	public static void registerBlock(RegistryEvent.Register<Block> event)
	{
		event.getRegistry().register(new BlockCeilingTorch().setRegistryName(MODID, "torch").setTranslationKey("torch"));
		event.getRegistry().register(new BlockRedstoneCeilingTorch(false).setRegistryName(MODID, "unlit_redstone_torch").setTranslationKey("notGate"));
		event.getRegistry().register(new BlockRedstoneCeilingTorch(true).setRegistryName(MODID, "redstone_torch").setTranslationKey("notGate"));
	}
}
